import subprocess
dir_list=["/Volumes/WyDriveBlue/Rilo Kiley/More Adventurous [2004] [CD]",
"/Volumes/WyDriveBlue/RJD2/The Horror [2009] [CD]",
"/Volumes/WyDriveBlue/RJD2/Deadringer [2002] [CD]",
"/Volumes/WyDriveBlue/Rolo Tomassi/Cosmology [2010] [CD]",
"/Volumes/WyDriveBlue/Roxy Music/Roxy Music [1999] [HDCD]",
"/Volumes/WyDriveBlue/Röyksopp/Senior [2010] [CD]",
"/Volumes/WyDriveBlue/Röyksopp/Melody A.M. [2001] [CD]",
"/Volumes/WyDriveBlue/Röyksopp/Junior [2009] [CD]",
"/Volumes/WyDriveBlue/Rubblebucket/Omega La La [2011] [CD]",
"/Volumes/WyDriveBlue/Rubblebucket/Survival Sounds [2014] [CD]",
"/Volumes/WyDriveBlue/Rufus Wainwright/Unfollow the Rules [2020] [CD]",
"/Volumes/WyDriveBlue/Run‐D.M.C_/Raising Hell [1986] [CD]",
"/Volumes/WyDriveBlue/Run‐D.M.C_/Run‐D.M.C. [1984] [CD]",
"/Volumes/WyDriveBlue/Rush/2112 [1988] [CD]",
"/Volumes/WyDriveBlue/Sam Cooke/Live at the Harlem Square Club, 1963 [1985] [CD]",
"/Volumes/WyDriveBlue/Santana/Santana [2007] [CD]",
"/Volumes/WyDriveBlue/SBTRKT/SBTRKT [2011] [CD]",
"/Volumes/WyDriveBlue/SBTRKT/Transitions [2014] [Digital Media]",
"/Volumes/WyDriveBlue/Sleigh Bells/Treats [2010] [CD]",
"/Volumes/WyDriveBlue/Smith Westerns/Dye It Blonde [2011] [CD]",
"/Volumes/WyDriveBlue/Snoop Dogg/Doggystyle [1993] [CD]",
"/Volumes/WyDriveBlue/Solange/Sol-Angel and the Hadley St. Dreams [2008] [CD]",
"/Volumes/WyDriveBlue/Spoon/Gimme Fiction [2005] [CD]",
"/Volumes/WyDriveBlue/St. Vincent/Strange Mercy [2011] [CD]",
"/Volumes/WyDriveBlue/St. Vincent/St. Vincent [2014] [CD]",
"/Volumes/WyDriveBlue/Stan Getz & Charlie Byrd/Jazz Samba [1994] [CD]",
"/Volumes/WyDriveBlue/Stan Getz & João Gilberto feat. Antônio Carlos Jobim/Getz_Gilberto [1997] [CD]",
"/Volumes/WyDriveBlue/Steely Dan/The Royal Scam [2000] [CD]",
"/Volumes/WyDriveBlue/Steely Dan/Pretzel Logic [1999] [CD]",
"/Volumes/WyDriveBlue/Steely Dan/Countdown to Ecstasy [1973] [12_ Vinyl]",
"/Volumes/WyDriveBlue/Stevie Wonder/Songs in the Key of Life [1984] [CD]",
"/Volumes/WyDriveBlue/Sublime/Sublime [1996] [CD]",
"/Volumes/WyDriveBlue/Sufjan Stevens/Illinois [2005] [CD]",
"/Volumes/WyDriveBlue/Sufjan Stevens/The Age of Adz [2010] [CD]",
"/Volumes/WyDriveBlue/Sufjan Stevens/Carrie & Lowell [2015] [CD]",
"/Volumes/WyDriveBlue/Sufjan Stevens/All Delighted People EP [2010] [CD]",
"/Volumes/WyDriveBlue/Surfer Blood/Tarot Classics [2011] [CD]",
"/Volumes/WyDriveBlue/Syd Barrett/The Madcap Laughs [1993] [CD]",
"/Volumes/WyDriveBlue/T. Rex/Electric Warrior [2003] [Hybrid SACD (CD layer)]",
"/Volumes/WyDriveBlue/Talking Heads/Fear of Music [1984] [CD]",
"/Volumes/WyDriveBlue/Talking Heads/Speaking in Tongues [1983] [CD]",
"/Volumes/WyDriveBlue/Talking Heads/Talking Heads_ 77 [1989] [CD]",
"/Volumes/WyDriveBlue/Talking Heads/Remain in Light [1983] [CD]",
"/Volumes/WyDriveBlue/Tame Impala/Innerspeaker [2010] [CD]",
"/Volumes/WyDriveBlue/Tame Impala/Lonerism [2012] [CD]",
"/Volumes/WyDriveBlue/Tame Impala/The Slow Rush [2020] [CD]",
"/Volumes/WyDriveBlue/Tame Impala/Currents [2015] [CD]",
"/Volumes/WyDriveBlue/Tears for Fears/The Hurting [1983] [CD]",
"/Volumes/WyDriveBlue/Television/Marquee Moon [1987] [CD]",
"/Volumes/WyDriveBlue/The Beach Boys/Pet Sounds [2009] [HDCD]",
"/Volumes/WyDriveBlue/The Beatles/A Hard Day’s Night [2009] [Enhanced CD]",
"/Volumes/WyDriveBlue/The Beatles/Abbey Road [2009] [Enhanced CD]",
"/Volumes/WyDriveBlue/The Beatles/Help! [1987] [CD]",
"/Volumes/WyDriveBlue/The Beatles/Let It Be [2009] [Enhanced CD]",
"/Volumes/WyDriveBlue/The Beatles/Magical Mystery Tour [2009] [Enhanced CD]",
"/Volumes/WyDriveBlue/The Beatles/Revolver [2009] [Enhanced CD]",
"/Volumes/WyDriveBlue/The Beatles/Sgt. Pepper’s Lonely Hearts Club Band [2009] [Enhanced CD]",
"/Volumes/WyDriveBlue/The Black Keys/El Camino [2011] [CD]",
"/Volumes/WyDriveBlue/The Clash/Combat Rock [1988] [CD]",
"/Volumes/WyDriveBlue/The Clash/London Calling [1979] [12_ Vinyl]",
"/Volumes/WyDriveBlue/The Clash/The Clash [2002] [CD]",
"/Volumes/WyDriveBlue/The Cure/Faith [1988] [CD]",
"/Volumes/WyDriveBlue/The Cure/Kiss Me Kiss Me Kiss Me [1987] [CD]",
"/Volumes/WyDriveBlue/The Doobie Brothers/The Very Best of The Doobie Brothers [2007] [CD]",
"/Volumes/WyDriveBlue/The Doors/L.A. Woman [1993] [CD]",
"/Volumes/WyDriveBlue/The Doors/The Soft Parade [2007] [CD]",
"/Volumes/WyDriveBlue/The Doors/Morrison Hotel [1970] [12_ Vinyl]",
"/Volumes/WyDriveBlue/The Flaming Lips/At War With the Mystics [2006] [CD]",
"/Volumes/WyDriveBlue/The Flaming Lips/The Soft Bulletin_ 5.1 [2006] [CD]",
"/Volumes/WyDriveBlue/The Flaming Lips/Yoshimi Battles the Pink Robots [2017] [Digital Media]",
"/Volumes/WyDriveBlue/The Jayhawks/Paging Mr. Proust [2016] [CD]",
"/Volumes/WyDriveBlue/The Jam/In the City [1997] [CD]",
"/Volumes/WyDriveBlue/The Kinks/The Kinks Are the Village Green Preservation Society [2000] [CD]",
"/Volumes/WyDriveBlue/The Radio Dept_/Clinging to a Scheme [2010] [CD]",
"/Volumes/WyDriveBlue/The Radio Dept_/Lesser Matters [2003] [CD]",
"/Volumes/WyDriveBlue/The Smiths/Meat Is Murder [1985] [CD]",
"/Volumes/WyDriveBlue/The Smiths/Strangeways, Here We Come [1987] [CD]",
"/Volumes/WyDriveBlue/The Smiths/The Queen Is Dead [1986] [12_ Vinyl]",
"/Volumes/WyDriveBlue/The Velvet Underground/The Velvet Underground & Nico [1996] [CD]",
"/Volumes/WyDriveBlue/The War on Drugs/Slave Ambient [2011] [CD]",
"/Volumes/WyDriveBlue/The White Stripes/White Blood Cells [2002] [CD]",
"/Volumes/WyDriveBlue/The White Stripes/Elephant [2003] [CD]",
"/Volumes/WyDriveBlue/The Who/Live at Leeds [1999] [CD]",
"/Volumes/WyDriveBlue/The Who/Quadrophenia [1985] [CD]",
"/Volumes/WyDriveBlue/The Who/Tommy [1990] [CD]",
"/Volumes/WyDriveBlue/Thelonious Monk/Brilliant Corners [2003] [12_ Vinyl]",
"/Volumes/WyDriveBlue/Thelonious Monk/Solo Monk [2008] [CD]",
"/Volumes/WyDriveBlue/Thelonious Monk/Thelonious Monk Trio [1988] [CD]",
"/Volumes/WyDriveBlue/Thundercat/Drunk [2017] [CD]",
"/Volumes/WyDriveBlue/Thundercat/It Is What It Is [2020] [Digital Media]",
"/Volumes/WyDriveBlue/Tom Petty and the Heartbreakers/Damn the Torpedoes [1991] [CD]",
"/Volumes/WyDriveBlue/Vampire Weekend/Vampire Weekend [2008] [CD]",
"/Volumes/WyDriveBlue/Vampire Weekend/Modern Vampires of the City [2013] [CD]",
"/Volumes/WyDriveBlue/Vampire Weekend/Contra [2010] [CD]",
"/Volumes/WyDriveBlue/Van Morrison/Moondance [2013] [CD]",
"/Volumes/WyDriveBlue/ZHU/GENERATIONWHY [2016] [Digital Media]",
"/Volumes/WyDriveBlue/Yuck/Yuck [2011] [CD]",
"/Volumes/WyDriveBlue/Yeah Yeah Yeahs/Fever to Tell [2003] [CD]",
"/Volumes/WyDriveBlue/Wilco/Yankee Hotel Foxtrot [2002] [Enhanced CD]",
"/Volumes/WyDriveBlue/Wilco/A Ghost Is Born [2004] [Enhanced CD]",
"/Volumes/WyDriveBlue/Wilco/A.M. [1995] [CD]",
"/Volumes/WyDriveBlue/Wilco/Schmilco [2016] [CD]",
"/Volumes/WyDriveBlue/Wilco/Sky Blue Sky [2007] [CD]",
"/Volumes/WyDriveBlue/Wilco/Star Wars [2015] [Digital Media]",
"/Volumes/WyDriveBlue/Wilco/Summerteeth [1999] [CD]",
"/Volumes/WyDriveBlue/Wilco/The Whole Love [2011] [CD]",
"/Volumes/WyDriveBlue/Wilco/Wilco (The Album) [2009] [CD]",
"/Volumes/WyDriveBlue/Whitney/Light Upon the Lake [2016] [CD]",
"/Volumes/WyDriveBlue/White Denim/Corsicana Lemonade [2013] [CD]",
"/Volumes/WyDriveBlue/Washed Out/Within and Without [2011] [CD]",
"/Volumes/WyDriveBlue/Violent Femmes/Violent Femmes [1987] [CD]",
"/Volumes/WyDriveBlue/Unknown Mortal Orchestra/Unknown Mortal Orchestra [2011] [CD]",
"/Volumes/WyDriveBlue/Tyler, the Creator/IGOR [2019] [Digital Media]",
"/Volumes/WyDriveBlue/Two Door Cinema Club/Tourist History [2010] [CD]",
"/Volumes/WyDriveBlue/TV on the Radio/Nine Types of Light [2011] [CD]",
"/Volumes/WyDriveBlue/TV on the Radio/Dear Science [2008] [CD]",
"/Volumes/WyDriveBlue/Toro y Moi/Causers of This [2010] [CD]",
"/Volumes/WyDriveBlue/Young Adult Fiction/Paradise Birds [2011] [Digital Media]"]



print("===> CONVERTING AUDIO...")

for it in dir_list:
    print("===> Processing dir:", it)
    try:
        result = subprocess.run(["./audioConvertDir.sh", it], capture_output=True)
        print(result.stdout)
    except subprocess.CalledProcessError as e:
        print(f"Error processing file {it}: {e}")